### ISSUE TITLE
Sign

### ISSUE THREAD

**Issue by trikko** [JackStouffer/stdxdecimal#1]
I think you should consider to switch sign from (0,1) to -1; 1, using an enum to improve readibilityand a function helper.
It seems you just use -1;1 for coefficient.

I read:
```d
sign = val >= 0 ? 0 : 1;
```
and
```d
sign = val < 0 ? 0 : 1;
```
With 1;-1 you can write:

```d
enum Sign : ubyte { POSITIVE = 1; NEGATIVE = -1; }
ubyte getSign(T)(T n) { n >= 0?Sign.POSITIVE:-Sign.NEGATIVE; }
// first case
sign =  getSign(val);
// Second case
sign = -getSign(val);
```
This seems less error-prone that inverting bool conditions, and you can use also sign to get some calc, of course.

**Comment by JackStouffer** [comment]
Sorry, but the [spec](http://speleotrove.com/decimal/damodel.html) is pretty specific here

> sign – a value which must be either 0 or 1, where 1 indicates that the number is negative or is the negative zero and 0 indicates that the number is zero or positive.

Plus, in the newest version of the code, I changed sign to a `bool` rather than a `ubyte`, which saves some space, which I can't do if sign needs to be `-1`.
